[package]
name = "ray_tracer"
version = "0.1.0"
edition = "2021"

[lib]
name = "ray_tracer"
path = "src/lib.rs"

[[bin]]
name = "ray_tracer"
path = "src/main.rs"

[dependencies]
rand = "0.9"
image = "0.25"
rayon = "1.10"
clap = { version = "4.5", features = ["derive"] }
